---

# yamllint disable rule:line-length
specfile_path: ../distro/stratis-cli.spec
merge_pr_in_ci: false
update_release: false

downstream_package_name: stratis-cli

actions:
  post-upstream-clone:
    - "git clone https://github.com/stratis-storage/ci --depth=1 ../distro"
    - "mv ../distro/mockbuild_test/stratis-cli.spec ../distro/stratis-cli.spec"
  create-archive:
    - "sh -c 'python3 ../distro/release_management/create_artifacts.py ../distro/ --pre-release --specfile-path=../distro/stratis-cli.spec stratis-cli'"
  fix-spec-file:
    - "echo 'skipping automatic fix-spec-file actions'"
  get-current-version:
    - "python3 setup.py --version"

srpm_build_deps:
  - python3-pip
  - git

jobs:
  - job: copr_build
    trigger: pull_request
    manual_trigger: true
    targets:
      - fedora-all
