---

# yamllint disable rule:line-length
specfile_path: ../distro/stratis-cli.spec
merge_pr_in_ci: false
update_release: false

downstream_package_name: stratis-cli

actions:
  post-upstream-clone:
    - "git clone https://github.com/stratis-storage/ci --depth=1 ../distro"
    - "bash -c '(cd ../distro; wget https://src.fedoraproject.org/rpms/stratis-cli/raw/rawhide/f/stratis-cli.spec)'"
  create-archive:
    - "sh -c 'python3 ../distro/release_management/create_artifacts.py ../distro/ --pre-release --specfile-path=../distro/stratis-cli.spec stratis-cli'"
  fix-spec-file:
    - "echo 'skipping automatic fix-spec-file actions'"
  get-current-version:
    - "python3 setup.py --version"

srpm_build_deps:
  - git
  - python3-pip
  - python3-semantic_version
  - wget2
  - wget2-wget

jobs:
  - job: copr_build
    trigger: pull_request
    identifier: copr_pull
    manual_trigger: true
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    identifier: copr_commit
    preserve_project: true
    targets:
      - fedora-all

notifications:
  pull_request:
    successful_build: true
