[default.extend-words]
# Misidentified as misspelling of "BE"
DBE = "DBE"

[default.extend-identifiers]
# Misidentified as misspelling of "on"
pn = "pn"

[files]
# typos tries to correct the spelling of D-Bus signatures
extend-exclude = ["_introspect.py"]
