#!/usr/bin/env python3

# Copyright 2021 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Get GetManagedObjects info as a json string
"""

# isort: STDLIB
import json
import xml.etree.ElementTree as ET

# isort: THIRDPARTY
import dbus

# isort: FIRSTPARTY
from dbus_python_client_gen import make_class

# a minimal chunk of introspection data, enough for the methods needed.
SPECS = {
    "org.freedesktop.DBus.ObjectManager": """
<interface name="org.freedesktop.DBus.ObjectManager">
    <method name="GetManagedObjects">
      <arg name="objpath_interfaces_and_properties" type="a{oa{sa{sv}}}" direction="out" />
    </method>
  </interface>
"""
}

_SERVICE = "org.storage.stratis2"

_OBJECT_MANAGER_IFACE = "org.freedesktop.DBus.ObjectManager"
_TIMEOUT = 120000

# pylint: disable=invalid-name
ObjectManager = make_class(
    "ObjectManager", ET.fromstring(SPECS[_OBJECT_MANAGER_IFACE]), _TIMEOUT
)


def main():
    """
    The main method.
    """
    bus = dbus.SystemBus()

    proxy = bus.get_object(_SERVICE, "/org/storage/stratis2", introspect=False)

    managed_objects = ObjectManager.Methods.GetManagedObjects(proxy, {})

    print(json.dumps(managed_objects))


if __name__ == "__main__":
    main()
