---
name: stratis-cli dummy CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - rebase-3.6.0
  pull_request:
    branches:
      - rebase-3.6.0

  workflow_dispatch:

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Run dummy test
        run: echo "I exist to be Required in Github branch protection rules"
