---
name: stratis-cli weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 25 3 * * 4
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  next-fedora-python-checks:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # PYTHON CHECKS ON NEXT FEDORA PYTHON AND PYTHON TOOLS VERSION
          - dependencies: >
              bandit
              pylint
              python3-dateutil
              python3-dbus-client-gen
              python3-dbus-python-client-gen
              python3-justbytes
              python3-packaging
              python3-psutil
              python3-pydantic
              python3-wcwidth
            task: >
              PATH=${PATH}:/github/home/.local/bin PYTHONPATH=./src
              make -f Makefile lint
          - dependencies: black python3-isort
            task: make -f Makefile fmt-ci
          - dependencies: shfmt
            task: make -f Makefile fmt-shell-ci
          - dependencies: yamllint
            task: make -f Makefile yamllint
    runs-on: ubuntu-latest
    container: fedora:40  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          dnf install -y
          make
          pip
          python-unversioned-command
          ${{ matrix.dependencies }}
      - name: Install pyright
        run: pip install --user pyright
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}
